general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/.config/archmac/wallpapers/current.jpg

    blur_passes = 2
    blur_size = 6

    brightness = 0.72
    contrast = 1.05
}

label {
    monitor =
    text = ARCHMAC
    font_family = 0xProto
    font_size = 16
    color = rgba(72d8ffff)

    position = 0, 190
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_family = 0xProto
    font_size = 58
    color = rgba(ffffffff)

    position = 0, 115
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date '+%A · %d %B %Y'
    font_family = 0xProto
    font_size = 15
    color = rgba(cbd5e1ff)

    position = 0, 66
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:3600000] echo "$(whoami)@$(hostname)"
    font_family = 0xProto
    font_size = 13
    color = rgba(94a3b8ff)

    position = 0, 30
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 280, 48
    outline_thickness = 2

    outer_color = rgba(72d8ffff)
    inner_color = rgba(0c0e12dd)
    font_color = rgba(ffffffff)

    check_color = rgba(72d8ffff)
    fail_color = rgba(ff5f6dff)

    placeholder_text = Password
    fail_text = Authentication failed

    dots_size = 0.22
    dots_spacing = 0.28
    dots_center = true

    position = 0, -55
    halign = center
    valign = center
}
